### ISSUE TITLE
Learn Javascript

### ISSUE THREAD

**Issue by FranciscoImanolSuarez** [maxwellainatchi/sorting-algorithm-tester#1]
I understand that it is not the case but, could this program be implemented to learn Javascript?

for example ask the user to write Hello World by console (console.log)

**Comment by FranciscoImanolSuarez** [comment]
I close since I was able to find a much clearer example

**Comment by maxwellainatchi** [comment]
Actually, I was planning on updating this to support multiple problemsets, but for now it was just to give my cousin a place to try to figure out how to write a sorting algorithm

**Comment by maxwellainatchi** [comment]
You should check out [HackerRank](https://www.hackerrank.com/) though, that's what inspired me to write this. I just needed to write my own problem for it, so I made my own

**Comment by FranciscoImanolSuarez** [comment]
Yes, I was inspired to create something like Codecademy or Freecodecamp, but it is VERY difficult to create the code editor

**Comment by maxwellainatchi** [comment]
I used the Monaco editor, which is what VSCode is based on, and created a sandbox environment to execute it in
